function oneOf(list: string[]): string {
    return list[Math.floor(Math.random() * list.length)];
}

export default function (): string {
    return (oneOf([
        '',
        '',
        '',
        'Fast',
        'Advanced',
        'Paid',
        'Pro',
        'Remote',
        'Secret',
        'Automatic',
        'Simple',
    ]) + ' ' + oneOf([
        'Post',
        'Discussion',
        'User',
        'Profile',
        'Tag',
        'Admin',
        'Webhook',
        'Spam',
        'Language',
        'BBCode',
        'Markdown',
        'Image',
        'Link',
        'URL',
        'File',
        'Header',
        'Login',
        'Logout',
        'Log',
        'Error',
        'Theme',
        'Layout',
    ]) + ' ' + oneOf([
        '',
        'Manager',
        'Generator',
        'Remover',
        'Optimization',
        'Blocker',
        'Detection',
        'Dropdown',
        'Menu',
        'Toolbar',
        'Creation',
        'Translator',
        'Rename',
        'Upload',
        'Download',
        'Downloader',
    ])).trim();
}
